### ISSUE TITLE
Building with FFI

### ISSUE THREAD

**Issue by jason-wolfe** [sampsyo/llvm-ei#1]
Hi,

Have you succeeded at running with libffi included?

Without it, I pretty much can't run any non-trivial program.

I've got it pointing at an llvm installation built with LLVM_ENABLE_FFI enabled, and patched up the CMakeLists.txt with `target_link_libraries( trace ${FFI_LIBRARY_PATH} )`, which got it to at least build.

But it still fails once it (very quickly) hits its first `@llvm.memcpy` with `LLVM ERROR: Tried to execute an unknown external function: memcpy`.

`lli` successfully interprets / executes the program. 

I'm wondering if it has to do with the `sys::DynamicLibrary::SearchForAddressOfSymbol` call in `callExternalFunction`. I've added debug output and the trace executable does run the code in the `#ifdef USE_LIBFFI` block.

**Comment by sampsyo** [comment]
Interesting. I actually haven't tried this, but I can see how it might be a problem. (I've been running definitively trivial programs so far.) I'll take a closer look when I get a chance—meanwhile, let me know if you come up with anything.

**Comment by jason-wolfe** [comment]
If I add a call to `sys::DynamicLibrary::LoadLibraryPermanently(0, NULL)` at the beginning of `ExtensibleInterpreter::RunFunction` then everything works. I discovered it in ExecutionEngine.cpp, and it's commented there with:

``` c++
  // Make sure we can resolve symbols in the program as well. The zero arg
  // to the function tells DynamicLibrary to load the program, not a library.
  if (sys::DynamicLibrary::LoadLibraryPermanently(0, ErrorStr))
    return 0;
```

I'm not sure if this is the best place for it, but it's at least something that gets called at the start of program execution.

This plus the CMakeLists.txt change to include libffi make everything work, as far as I can tell so far. I guess the proper route is to add documentation for configuring/compiling llvm with LLVM_ENABLE_FFI and add this to the default CMakeLists.txt?

**Comment by sampsyo** [comment]
Aha. Great find; I must have missed this the firs time through. Yes, it sounds like we should add that call and compile with [that option](http://llvm.org/docs/CMake.html#llvm-specific-variables). I'll give you commit access so you can make these changes if you already have them locally, but I'd also be happy to implement them if you prefer.
